"""add video support and extend comments

Revision ID: f80d31156bb1
Revises: 883eabbd4fa5
Create Date: 2026-09-01 05:04:33.712636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80d31156bb1'
down_revision: Union[str, None] = '883eabbd4fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('poster_object_key', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_videos_category'), 'videos', ['category'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_table('video_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'customer_id', name='uq_video_likes_video_customer')
    )
    op.create_index(op.f('ix_video_likes_customer_id'), 'video_likes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_video_likes_video_id'), 'video_likes', ['video_id'], unique=False)
    op.create_table('video_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('viewer_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'viewer_key', name='uq_video_views_video_viewer')
    )
    op.create_index(op.f('ix_video_views_video_id'), 'video_views', ['video_id'], unique=False)
    op.create_index(op.f('ix_video_views_viewer_key'), 'video_views', ['viewer_key'], unique=False)
    op.add_column('comments', sa.Column('video_id', sa.String(length=36), nullable=True))
    op.alter_column('comments', 'photo_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_comments_video_id'), 'comments', ['video_id'], unique=False)
    op.create_foreign_key(
        'fk_comments_video_id_videos', 'comments', 'videos', ['video_id'], ['id'], ondelete='CASCADE'
    )
    # Autogenerate does NOT detect table-level CheckConstraint changes on
    # an existing table (only column/table/index/FK additions) -- this
    # has to be added by hand. Matches Comment.__table_args__ exactly:
    # a comment belongs to exactly one photo or one video, never both,
    # never neither.
    op.create_check_constraint(
        'ck_comments_exactly_one_media',
        'comments',
        '(photo_id IS NOT NULL AND video_id IS NULL) OR (photo_id IS NULL AND video_id IS NOT NULL)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_comments_exactly_one_media', 'comments', type_='check')
    op.drop_constraint('fk_comments_video_id_videos', 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_video_id'), table_name='comments')
    op.alter_column('comments', 'photo_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('comments', 'video_id')
    op.drop_index(op.f('ix_video_views_viewer_key'), table_name='video_views')
    op.drop_index(op.f('ix_video_views_video_id'), table_name='video_views')
    op.drop_table('video_views')
    op.drop_index(op.f('ix_video_likes_video_id'), table_name='video_likes')
    op.drop_index(op.f('ix_video_likes_customer_id'), table_name='video_likes')
    op.drop_table('video_likes')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_category'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
